### ISSUE TITLE
wrong duration of `.mp3` and `.wav`

### ISSUE THREAD

**Issue by jerry7536** [benrr101/node-taglib-sharp#95] opened 2023-12-01 08:54 UTC
[samples.zip](https://github.com/benrr101/node-taglib-sharp/files/13523037/samples.zip)
there are two audio files, the duration are all 3 seconds. but `file.properties.durationMilliseconds` is `6110` for `.mp3` and `6000` for `.wav`

but in https://audio-tag-analyzer.netlify.app/ they are correctly read

**Comment by benrr101** [comment] 2023-12-20 19:34
@jerry7536 Thanks for reporting this. Based on the investigation @subframe7536 did, it looks like this is caused by Xing headers being used in certain CBR files and using the `Info` identifier for the header rather than `Xing`. @subframe7536 has a PR out that fixes the issue, I think, though I want to run a couple more tests and consider tweaking how we report the description. (ie, if a Xing or VBR header are present, the file is marked as VBR, even if the Xing header is for a CBR. Small issue, but it'd be nice to address it.)

Once those tests are sorted out, I'll get a new build out.

**Closed** 2024-01-17 06:15 UTC
Labels: bug
